"""Fails if README.md's scorecard table drifts from evaluation/results/scorecard.md.

evaluation/results/scorecard.md is generated by `make eval` and is the
single source of truth for every gate number (evaluation/README.md's
"Reading the scorecard" section). This just enforces that promise: if the
scorecard changes, README.md must be updated to match in the same push.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
# Table shape (both files): | Gate | Description | Internal target | Result [mark] |
# Skip the Description and Internal-target columns to land on Result, not
# accidentally capture the target number instead.
GATE_RE = re.compile(r"\|\s*(G[1-6])\s*\|[^|]*\|[^|]*\|\s*(\d+(?:\.\d+)?)")


def parse_gates(text: str) -> dict[str, float]:
    return {gate: float(value) for gate, value in GATE_RE.findall(text)}


def main() -> int:
    scorecard = parse_gates((ROOT / "evaluation/results/scorecard.md").read_text(encoding="utf-8"))
    readme = parse_gates((ROOT / "README.md").read_text(encoding="utf-8"))

    missing = set(scorecard) - set(readme)
    if missing:
        print(f"README.md is missing gate(s) present in scorecard.md: {sorted(missing)}")
        return 1

    mismatched = [
        gate for gate, value in scorecard.items() if readme.get(gate) != value
    ]
    if mismatched:
        for gate in mismatched:
            print(f"{gate}: scorecard.md={scorecard[gate]} README.md={readme.get(gate)}")
        print("README.md's scorecard table is out of sync with evaluation/results/scorecard.md.")
        return 1

    print(f"OK — README.md matches scorecard.md for {sorted(scorecard)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
